[master]
n_jobs = 4
cache_size = 100
meta_timeout = "10s"
dashboard_user_name = "admin"
dashboard_password = "admin"

[database]
data_store = "postgres://gorse:gorse@postgres:5432/gorse?sslmode=disable"
cache_store = "redis://redis:6379"

[recommend]
check_recommend_period = "1m"
refresh_recommend_period = "5m"
popular_window = "720h"
fit_period = "1h"
search_period = "30m"
search_epoch = 50
